name: Build Release

on:
  push:
    branches: [ master ]
  workflow_dispatch: # Cho phép bấm nút "Run workflow" thủ công bất cứ lúc nào trên giao diện web GitHub

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Release (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Package Payload into IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r SportO-Cam-iOS.ipa Payload
          rm -rf Payload

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: SportO-Cam-iOS-ipa
          path: SportO-Cam-iOS.ipa
